### ISSUE TITLE
Consider securing CHIRP further.

### ISSUE THREAD

**Issue by PrinceMaren1** [ITU-BDSA23-GROUP21/Chirp#151]
As a developer i want my program to be safe from things such as cross-site scripting (XXS) and SQL injection attacks.

We as a team need to consider if we need further security for our program, or if we have the necessary security.
Consider reading chapters 29.1 and 29.4.2 in the course book to see possible security options.

Acceptance critria:
-  Chirp is safe from SQL injection attacks andn cross-site scripting (XXS)

**Comment by tbr2** [comment]
We are safe from SQL injection, but we will look a bit more into XSS before closing this task.

**Comment by tbr2** [comment]
Looking at microsofts recommendations for preventing XSS in razor, we seem to be following the recommendations. (see https://learn.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-8.0)

Html encoding is handled by using the Razor @ directive, and we don't have any places where user defined values are inserted into javascript or url's
