### ISSUE TITLE
User information page with "forget me!" button

### ISSUE THREAD

**Issue by chrolle69** [ITU-BDSA23-GROUP21/Chirp#183]
as a user i would like to see what information the software collects about me by having a page with all the my information.

Acceptance criteria:
- make a razor page with all user data
- razor page contains: name, email, cheeps, following/followers
- make a "Forget me!" button that annonymize all the personal info of that user

**Comment by tbr2** [comment]
Merging PR now, but there are still an outstanding issue. The redirect url is hardcoded using localhost, this needs to be changed to be environment dependent.

**Comment by tbr2** [comment]
We don't delete users in azure AD, but this is fine for now. We will create another issue for this.
