### ISSUE TITLE
As a developer, I want higher cohesion and lower coupling so that the program is more navigatable and readable.

### ISSUE THREAD

**Issue by EngboITU** [ITU-BDSA23-GROUP21/Chirp#3]
In order to achieve a more navigatable and readable program as a developer, I can refactor the User Interface code so that it exists in a separate file.

Acceptance criteria:
 * User Interface is in a separate file from the rest of the code

**Comment by tbr2** [comment]
Closed as it's a duplicate of #2

**Comment by tbr2** [comment]
Closed as it's a duplicate of #2
